---
driver:
  name: docker
driver_config:
  require_chef_omnibus: true
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list: ['ectg-base::default']