---
driver:
  name: docker
driver_config:
  require_chef_omnibus: true
  use_sudo: false
  privileged: true #required for iptables stuff. this is safe since we're just using docker to make local converge faster

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
  - name: ubuntu-14.04
    run_list: apt

suites:
  - name: default
    run_list: ['ectg-iptables::sshd-world','ectg-base::default']