name 'ectg-base'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'mit'
description 'Installs/Configures ectg-base'
long_description 'Installs/Configures ectg-base'
version '0.0.1'

depends 'yum-epel'
depends 'vim'
depends 'ntp'
depends 'openssh'
depends 'curl'
depends 'postfix'
depends 'chef-client'
depends 'build-essential'
depends 'iptables'
depends 'git'
depends 'nodejs'
depends 'selinux'
depends 'monit'
depends 'users'
depends 'openssl'
depends 'sudo'
