name 'mwser-base'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'apachev2'
description 'Installs/Configures mwser-base'
long_description 'Installs/Configures mwser-base'
version '0.3.3'

supports 'ubuntu', '>= 12.04'
supports 'centos', '~> 6.7'

depends 'yum-epel', '~> 0.6.6'
depends 'vim'
depends 'ntp'
depends 'openssh'
depends 'curl'
depends 'postfix'
depends 'chef-client'
depends 'build-essential'
depends 'git'
depends 'nodejs'
depends 'selinux'
depends 'monit'
depends 'users'
depends 'openssl'
depends 'sudo', '~> 2.7.2'
depends 'mwser-iptables'
depends 'timezone-ii'
